Repository lf-lang/lingua-franca, pull requests merged in 2022-09, with the labels that each got.

#1343 Updated IntelliJ code styles
  .idea/codeStyles/Project.xml
Labels: enhancement

#1349 Improve error messaging for mode validation
  org.lflang.tests/src/org/lflang/tests/compiler/LinguaFrancaValidationTest.java
  org.lflang/src/org/lflang/validation/LFValidator.java
Labels: enhancement, validation, modal models

#1356 Reduction of output in formatter tests
  org.lflang.tests/src/org/lflang/tests/compiler/RoundTripTests.java
  org.lflang.tests/src/org/lflang/tests/lsp/LspTests.java
Labels: testing, exclude, ci

#1351 Exclude reactor runtime module from the Rust test modules
  test/Rust/src-gen/Cargo.toml
Labels: rust, bugfix

#1358 Only record tests in test/*/src
  org.lflang.tests/src/org/lflang/tests/TestRegistry.java
  org.lflang.tests/src/org/lflang/tests/compiler/RoundTripTests.java
Labels: testing

#1352 Fix problem with child dependencies in Rust
  org.lflang/src/org/lflang/generator/rust/RustReactorEmitter.kt
  test/Rust/src/DependencyThroughChildPort.lf
  test/Rust/src/README.md
Labels: rust, bugfix

#1365 Removal of unnecessary build dependency to address security exceptions
  gradle.properties
  org.lflang/META-INF/MANIFEST.MF
  org.lflang/build.gradle
  org.lflang/pom.xml
  pom.xml
Labels: gradle, bugfix

#1370 Adjustment of code generator to address #1368
  org.lflang/src/org/lflang/generator/c/CTriggerObjectsGenerator.java
  test/C/src/MultipleOutputs.lf
Labels: bugfix

#1364 Xtext to 2.18.0, LSP4J to 0.15.0, and Guice to 5.1.0
  gradle.properties
Labels: upgrade

#1381 Use debug logging for all LF tests run in CI
  org.lflang.cli/src/org/lflang/cli/Lfc.java
  org.lflang.tests/src/org/lflang/tests/LFTest.java
  org.lflang.tests/src/org/lflang/tests/TestBase.java
  org.lflang/src/org/lflang/generator/GeneratorUtils.java
  test/C/src/Deadline.lf
  test/C/src/DeadlineHandledAbove.lf
  test/C/src/TimeLimit.lf
  test/C/src/concurrent/DeadlineHandledAboveThreaded.lf
  test/C/src/concurrent/DeadlineThreaded.lf
  test/C/src/concurrent/TimeLimitThreaded.lf
  test/C/src/federated/DistributedCountDecentralizedLate.lf
  test/C/src/federated/DistributedCountDecentralizedLateHierarchy.lf
  test/Cpp/src/TimeLimit.lf
  test/Cpp/src/concurrent/TimeLimitThreaded.lf
  test/Python/src/Deadline.lf
  test/Python/src/DeadlineHandledAbove.lf
  test/Python/src/TimeLimit.lf
Labels: enhancement, ci
