Repository lf-lang/lingua-franca, pull requests merged in 2022-08, with the labels that each got.

#1310 Removal of error reporting markers from parameter types
  org.lflang/src/org/lflang/generator/TargetTypes.java
Labels: bugfix

#1324 Fix layout for error messsage node
  org.lflang.diagram/src/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java
Labels: diagrams, bugfix

#1300 Custom icons for reactors in diagrams
  org.lflang.diagram/src/org/lflang/diagram/synthesis/util/ReactorIcons.java
  org.lflang/src/org/lflang/AttributeUtils.java
  org.lflang/src/org/lflang/util/FileUtil.java
  org.lflang/src/org/lflang/validation/AttributeSpec.java
  org.lflang/src/org/lflang/validation/LFValidator.java
Labels: diagrams, feature
