Repository lf-lang/lingua-franca, pull requests merged in 2022-07, with the labels that each got.

#1241 Adjust reset symbols in diagrams
  org.lflang.diagram/src/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java
  org.lflang.diagram/src/org/lflang/diagram/synthesis/styles/LinguaFrancaShapeExtensions.java
Labels: diagrams

#1266 Clean up after #1265
  org.lflang/src/org/lflang/util/LFCommand.java
Labels: exclude

#1274 Deactivate middle position for labels on unconnencted ports
  org.lflang.diagram/src/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java
Labels: diagrams

#1285 Do not minimize the shadow jar
  org.lflang.lfc/build.gradle
Labels: bug, gradle

#1279 Fix banks of modal reactors
  org.lflang/src/org/lflang/generator/c/CGenerator.java
  org.lflang/src/org/lflang/generator/c/CModesGenerator.java
  org.lflang/src/org/lflang/generator/c/CStateGenerator.java
  org.lflang/src/org/lflang/generator/c/CTriggerObjectsGenerator.java
  org.lflang/src/org/lflang/generator/python/PythonPortGenerator.java
  test/C/src/modal_models/BanksCount3ModesComplex.lf
  test/C/src/modal_models/BanksCount3ModesSimple.lf
  test/C/src/modal_models/BanksModalStateReset.lf
  test/Python/src/modal_models/BanksCount3ModesComplex.lf
  test/Python/src/modal_models/BanksCount3ModesSimple.lf
  test/Python/src/modal_models/BanksModalStateReset.lf
  test/Python/src/modal_models/ModalStateResetAuto.lf
Labels: modal models

#1286 Cpp: fix triggering of reactions in multiple nested reactors
  test/C/src/Hierarchy.lf
  test/C/src/NestedTriggeredReactions.lf
  test/Cpp/src/NestedTriggeredReactions.lf
Labels: bug, c++

#1297 Bump Klighd version to 2.2
  oomph/LinguaFranca.setup
  org.lflang.diagram/META-INF/MANIFEST.MF
  org.lflang.diagram/src/org/lflang/diagram/synthesis/SynthesisRegistration.java
  org.lflang.diagram/src/org/lflang/diagram/synthesis/action/FilterCycleAction.java
  org.lflang.diagram/src/org/lflang/diagram/synthesis/postprocessor/ReactionPortAdjustment.java
  org.lflang.diagram/src/org/lflang/diagram/synthesis/styles/LinguaFrancaStyleExtensions.java
  org.lflang.targetplatform/org.lflang.targetplatform.target
Labels: diagrams

#1303 Fix to ensure the ordering of reactions relative to modes is correct
  org.lflang/src/org/lflang/ASTUtils.java
  test/C/src/modal_models/MixedReactions.lf
Labels: modal models, bugfix

#1304 Slightly more informational output of `package_lfc` script
  .github/scripts/package_lfc.sh
Labels: exclude

#1218 Compile Rust projects with Rust stable
  .github/workflows/rs-tests.yml
  org.lflang/src/org/lflang/generator/rust/RustEmitter.kt
  org.lflang/src/org/lflang/generator/rust/RustGenerator.kt
  org.lflang/src/org/lflang/generator/rust/RustModel.kt
  org.lflang/src/org/lflang/generator/rust/RustValidator.kt
Labels: rust
