Repository lf-lang/lingua-franca, pull requests merged in 2022-10, with the labels that each got.

#1387 Switch to own provider plugin for external dependencies
  oomph/LinguaFranca.setup
  org.lflang.lds/category.xml
  org.lflang.sdk/feature.xml
  org.lflang.targetplatform/org.lflang.targetplatform.target
  org.lflang/META-INF/MANIFEST.MF
  org.lflang/src/org/lflang/generator/rust/RustGenerator.kt
Labels: enhancement, epoch

#1391 Repair of Windows diagnostic reporting
  org.lflang/src/org/lflang/generator/CodeMap.java
Labels: windows, bugfix

#1384 Augmented Support for Arduino
  org.lflang.tests/src/org/lflang/tests/compiler/LinguaFrancaValidationTest.java
  org.lflang/src/org/lflang/TargetConfig.java
  org.lflang/src/org/lflang/TargetProperty.java
  org.lflang/src/org/lflang/generator/c/CCmakeCompiler.java
  org.lflang/src/org/lflang/generator/c/CCmakeGenerator.java
  org.lflang/src/org/lflang/generator/c/CGenerator.java
  org.lflang/src/org/lflang/generator/c/CMainGenerator.java
  org.lflang/src/org/lflang/generator/c/CPreambleGenerator.java
  test/C/src/arduino/BlinkCustomPlatform.lf
  test/C/src/arduino/BoardOptions.cmake
Labels: enhancement

#1401 Removal of obsolete Eclipse installation files and formatter
  JavaFormatterEclipse.xml
  LinguaFrancaProjectSetHTTPS.psf
  LinguaFrancaProjectSetSSH.psf
Labels: exclude, cleanup

#1404 Handling for commented-out reactions in integration tests
  org.lflang.tests/src/org/lflang/tests/lsp/ErrorInserter.java
Labels: exclude, ci, bugfix

#1425 Fixed NPE in Epoch
  org.lflang/src/org/lflang/generator/CodeMap.java
Labels: bugfix

#1422 New lff script and `org.lflang.cli` moved into `org.lflang` as subpackage
  .github/scripts/package-cli.sh
  .github/scripts/test-build.sh
  .github/scripts/test-lfc.sh
  .github/scripts/test-lff.sh
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/cli-tests.yml
  bin/build-lf-cli
  bin/lfc.ps1
  bin/lff
  bin/lff.ps1
  build.gradle
  lib/scripts/build.sh
  lib/scripts/include.sh
  lib/scripts/launch.ps1
  lib/scripts/launch.sh
  org.lflang.cli/build.gradle
  org.lflang.tests/build.gradle
  org.lflang.tests/resources/org/lflang/tests/cli/colors.lf
  org.lflang.tests/resources/org/lflang/tests/cli/colors.stderr
  org.lflang.tests/resources/org/lflang/tests/cli/emptyFile.lf
  org.lflang.tests/resources/org/lflang/tests/cli/emptyFile.stderr
  org.lflang.tests/resources/org/lflang/tests/cli/issue490.lf
  org.lflang.tests/resources/org/lflang/tests/cli/issue490.stderr
  org.lflang.tests/resources/org/lflang/tests/cli/multilineWarning.lf
  org.lflang.tests/resources/org/lflang/tests/cli/multilineWarning.stderr
  org.lflang.tests/resources/org/lflang/tests/cli/multilineWarningTooBig.lf
  org.lflang.tests/resources/org/lflang/tests/cli/multilineWarningTooBig.stderr
  org.lflang.tests/resources/org/lflang/tests/cli/simpleWarning.lf
  org.lflang.tests/resources/org/lflang/tests/cli/simpleWarning.stderr
  org.lflang.tests/resources/org/lflang/tests/cli/tabs.lf
  org.lflang.tests/resources/org/lflang/tests/cli/tabs.stderr
  org.lflang.tests/resources/org/lflang/tests/cli/twoLineWarning.lf
  org.lflang.tests/resources/org/lflang/tests/cli/twoLineWarning.stderr
  org.lflang.tests/src/org/lflang/tests/cli/LfcIssueReportingTest.kt
  org.lflang/build.gradle
  org.lflang/src/org/lflang/cli/CliBase.java
  org.lflang/src/org/lflang/cli/LFStandaloneModule.java
  org.lflang/src/org/lflang/cli/Lfc.java
  org.lflang/src/org/lflang/cli/Lff.java
  org.lflang/src/org/lflang/cli/ReportingUtil.kt
  org.lflang/src/org/lflang/cli/StandaloneErrorReporter.java
  org.lflang/src/org/lflang/cli/StandaloneIssueAcceptor.java
Labels: enhancement, refactoring
