Repository lf-lang/lingua-franca, pull requests merged in 2022-11, with the labels that each got.

#1440 Package `org.lflang.cli` excluded from Eclipse build configuration
  org.lflang/.classpath
Labels: build system, epoch

#1439 Empty bracket pairs properly tokenized
  org.lflang.tests/src/org/lflang/tests/compiler/LinguaFrancaParsingTest.java
  org.lflang/src/org/lflang/LinguaFranca.xtext
Labels: language

#1445 Fixed javadoc and NPE on toString
  org.lflang/src/org/lflang/federated/FederateInstance.java
Labels: bugfix

#1452 Fix TS CI on Windows
  .github/workflows/ci.yml
  .github/workflows/ts-tests.yml
Labels: ci, bugfix

#1411 Differentiation between multi-threaded and single-threaded preprocessor directives in C
  org.lflang/src/org/lflang/generator/c/CCmakeGenerator.java
Labels: c

#1457 TypeScript generator cleanups
  org.lflang/src/org/lflang/CommonExtensions.kt
  org.lflang/src/org/lflang/generator/ExpressionGenerator.java
  org.lflang/src/org/lflang/generator/GeneratorUtils.kt
  org.lflang/src/org/lflang/generator/TargetTypes.java
  org.lflang/src/org/lflang/generator/cpp/CppAssembleMethodGenerator.kt
  org.lflang/src/org/lflang/generator/cpp/CppInstanceGenerator.kt
  org.lflang/src/org/lflang/generator/cpp/CppPortGenerator.kt
  org.lflang/src/org/lflang/generator/cpp/CppReactionGenerator.kt
  org.lflang/src/org/lflang/generator/cpp/CppRos2PackageGenerator.kt
  org.lflang/src/org/lflang/generator/cpp/CppStandaloneCmakeGenerator.kt
  org.lflang/src/org/lflang/generator/rust/RustCargoTomlEmitter.kt
  org.lflang/src/org/lflang/generator/rust/RustEmitter.kt
  org.lflang/src/org/lflang/generator/rust/RustMainFileEmitter.kt
  org.lflang/src/org/lflang/generator/rust/RustReactorEmitter.kt
  org.lflang/src/org/lflang/generator/ts/TSActionGenerator.kt
  org.lflang/src/org/lflang/generator/ts/TSConstructorGenerator.kt
  org.lflang/src/org/lflang/generator/ts/TSExtensions.kt
  org.lflang/src/org/lflang/generator/ts/TSGenerator.kt
  org.lflang/src/org/lflang/generator/ts/TSImportPreambleGenerator.kt
  org.lflang/src/org/lflang/generator/ts/TSInstanceGenerator.kt
  org.lflang/src/org/lflang/generator/ts/TSParameterGenerator.kt
  org.lflang/src/org/lflang/generator/ts/TSParameterPreambleGenerator.kt
  org.lflang/src/org/lflang/generator/ts/TSPortGenerator.kt
  org.lflang/src/org/lflang/generator/ts/TSReactionGenerator.kt
  org.lflang/src/org/lflang/generator/ts/TSReactorGenerator.kt
  org.lflang/src/org/lflang/generator/ts/TSStateGenerator.kt
  org.lflang/src/org/lflang/generator/ts/TSTimerGenerator.kt
  org.lflang/src/org/lflang/generator/ts/TSTypes.kt
Labels: refactoring

#1469 Switched to Gradle for language and diagram server build
  gradle.properties
  org.lflang.diagram/META-INF/MANIFEST.MF
  org.lflang.diagram/build.gradle
  org.lflang.diagram/src/META-INF/services/de.cau.cs.kieler.klighd.IKlighdStartupHook
  org.lflang.diagram/src/org/lflang/diagram/lsp/LanguageDiagramServer.java
  org.lflang.diagram/src/org/lflang/diagram/synthesis/util/ReactorIcons.java
  org.lflang.ide/build.gradle
  org.lflang.lds/.project
  org.lflang.lds/category.xml
  org.lflang.lds/pom.xml
  org.lflang.lds/uberjar.py
  pom.xml
  settings.gradle
Labels: build system, gradle

#1467 Add CLI unit tests
  org.lflang.tests/src/org/lflang/tests/TestUtils.java
  org.lflang.tests/src/org/lflang/tests/cli/CliToolTestFixture.java
  org.lflang.tests/src/org/lflang/tests/cli/LfcCliTest.java
  org.lflang.tests/src/org/lflang/tests/cli/LfcIssueReportingTest.kt
  org.lflang.tests/src/org/lflang/tests/cli/LffCliTest.java
  org.lflang/src/org/lflang/FileConfig.java
  org.lflang/src/org/lflang/cli/CliBase.java
  org.lflang/src/org/lflang/cli/LFStandaloneModule.java
  org.lflang/src/org/lflang/cli/Lfc.java
  org.lflang/src/org/lflang/cli/Lff.java
  org.lflang/src/org/lflang/cli/ReportingUtil.kt
  org.lflang/src/org/lflang/generator/c/CCompiler.java
Labels: testing

#1470 Cleanup AttributeUtils
  org.lflang.diagram/src/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java
  org.lflang.diagram/src/org/lflang/diagram/synthesis/util/ReactorIcons.java
  org.lflang/src/org/lflang/ASTUtils.java
  org.lflang/src/org/lflang/AstExtensions.kt
  org.lflang/src/org/lflang/AttributeUtils.java
  org.lflang/src/org/lflang/LinguaFranca.xtext
  org.lflang/src/org/lflang/ast/IsEqual.java
  org.lflang/src/org/lflang/ast/ToLf.java
  org.lflang/src/org/lflang/generator/rust/RustModel.kt
  org.lflang/src/org/lflang/util/StringUtil.java
  org.lflang/src/org/lflang/validation/AttributeSpec.java
  org.lflang/src/org/lflang/validation/LFValidator.java
Labels: enhancement

#1484 Fixing the loss of the hostname that is specified in a federated lf f…
  org.lflang/src/org/lflang/federated/generator/FedGenerator.java
Labels: bug, c, federated, docker

#1490 Avoid reading the same input stream twice
  org.lflang/src/org/lflang/util/FileUtil.java
Labels: bugfix

#1485 Fix tracing
  util/tracing/makefile
Labels: c, bugfix
