Repository lf-lang/lingua-franca, pull requests merged in 2022-05, with the labels that each got.

#1128 Release
  org.lflang.product/plugin.xml
Labels: exclude

#1131 Fixed a few calls to deprecated functions that were missed
  org.lflang/src/org/lflang/federated/serialization/FedNativePythonSerialization.java
  org.lflang/src/org/lflang/generator/c/CTriggerObjectsGenerator.java
  org.lflang/src/org/lflang/generator/python/PythonPortGenerator.java
  org.lflang/src/org/lflang/generator/python/PythonReactionGenerator.java
Labels: bug, c, python

#1152 Have Epoch welcome page point to website rather than wiki page
  org.lflang.product/intro/content.xml
Labels: epoch

#1164 Restore the ability to put the RTI on a remote machine
  org.lflang/src/org/lflang/federated/launcher/FedLauncher.java
Labels: federated

#1208 Use `toOriginalText` in `org.lflang.diagram`.
  org.lflang.diagram/src/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java
  org.lflang.diagram/src/org/lflang/diagram/synthesis/styles/LinguaFrancaShapeExtensions.java
  org.lflang/src/org/lflang/InferredType.java
Labels: invalid, ide, exclude
