Repository lf-lang/lingua-franca, pull requests merged in 2022-12, with the labels that each got.

#1476 Stop unpacking Rust runtime
  .github/workflows/ci.yml
  .github/workflows/rs-tests.yml
  gradle/source-layout.gradle
  org.lflang/build.gradle
  org.lflang/src/lib/rs/runtime-version.properties
  org.lflang/src/org/lflang/generator/LanguageRuntimeVersions.kt
  org.lflang/src/org/lflang/generator/rust/CargoDependencySpec.java
  org.lflang/src/org/lflang/generator/rust/RustGenerator.kt
  org.lflang/src/org/lflang/generator/rust/RustModel.kt
Labels: rust

#1501 CI formatting check disabled
  .github/workflows/ci.yml
Labels: exclude, ci

#1451 Fix for broken deadline propagation mechanism
  org.lflang.diagram/src/org/lflang/diagram/synthesis/styles/LinguaFrancaShapeExtensions.java
  org.lflang/src/org/lflang/generator/GeneratorBase.java
  org.lflang/src/org/lflang/generator/GeneratorUtils.java
  org.lflang/src/org/lflang/generator/ReactionInstance.java
  org.lflang/src/org/lflang/generator/ReactionInstanceGraph.java
  org.lflang/src/org/lflang/generator/ReactorInstance.java
  org.lflang/src/org/lflang/generator/c/CGenerator.java
  org.lflang/src/org/lflang/generator/c/CTriggerObjectsGenerator.java
  test/C/src/DeadlineInherited.lf
  test/C/src/DeadlinePriority.lf
  test/C/src/DeadlineWithAfterDelay.lf
  test/C/src/DeadlineWithBanks.lf
Labels: c, bugfix

#1517 Make Cmake output less verbose by suppressing install messages
  org.lflang/src/org/lflang/generator/c/CCmakeGenerator.java
  org.lflang/src/org/lflang/generator/cpp/CppStandaloneCmakeGenerator.kt
Labels: enhancement, cmake

#1519 C ClockSync test removed from CI
  test/C/src/federated/failing/ClockSync.lf
Labels: ci
