Repository lf-lang/lingua-franca, pull requests merged in 2023-12, with the labels that each got.

#2123 Fix ROS2 CI Setup
  .github/actions/setup-ros2/action.yml
Labels: exclude, ci

#2122 Fix bug: set length on incoming token
  core/src/main/java/org/lflang/generator/c/CReactionGenerator.java
Labels: bugfix

#2111 Type check error turned into warning
  core/src/main/java/org/lflang/validation/LFValidator.java
  core/src/test/java/org/lflang/tests/compiler/LinguaFrancaValidationTest.java
Labels: bugfix

#2137 Adjustment to test output to show progress
  core/src/testFixtures/java/org/lflang/tests/TestBase.java
Labels: testing

#2141 Time limits imposed on integration tests
  .github/workflows/c-tests.yml
  .github/workflows/cpp-tests.yml
  .github/workflows/rs-tests.yml
  .github/workflows/ts-tests.yml
Labels: testing

#2135 Fix comment in RunSingleTest
  core/src/integrationTest/java/org/lflang/tests/RunSingleTest.java
Labels: exclude

#2133 Sponsorship through OpenCollective
  .github/FUNDING.yml
Labels: exclude

#2130 Bugfix for TypeScript in dev mode
  codecov.yml
  core/src/main/kotlin/org/lflang/generator/ts/TSGenerator.kt
Labels: bugfix
