Repository lf-lang/lingua-franca, pull requests merged in 2023-07, with the labels that each got.

#1857 Unknown port types handled with `unknown` instead of `Present`
  core/src/main/java/org/lflang/Target.java
  core/src/main/java/org/lflang/generator/TargetTypes.java
  core/src/main/java/org/lflang/generator/ts/TSTypes.java
  core/src/main/kotlin/org/lflang/generator/ts/TSDelayBodyGenerator.kt
  core/src/main/kotlin/org/lflang/generator/ts/TSExtensions.kt
  core/src/main/kotlin/org/lflang/generator/ts/TSImportPreambleGenerator.kt
  core/src/main/kotlin/org/lflang/generator/ts/TSReactionGenerator.kt
  core/src/main/kotlin/org/lflang/generator/ts/TSTimerGenerator.kt
Labels: typescript

#1894 C math lib always linked for C target
  core/src/main/java/org/lflang/TargetConfig.java
  core/src/main/java/org/lflang/generator/c/CCmakeGenerator.java
  core/src/main/java/org/lflang/generator/c/CCompiler.java
  core/src/main/java/org/lflang/generator/c/CGenerator.java
  test/C/src/target/Math.lf
Labels: enhancement, c

#1896 Updated comments in response to review of #1891
  core/src/main/java/org/lflang/federated/generator/FederateInstance.java
Labels: exclude
