Repository lf-lang/lingua-franca, pull requests merged in 2023-02, with the labels that each got.

#1584 More robust ROS2 setup in CI
  .github/actions/setup-ros2/action.yml
  .github/workflows/ci.yml
  .github/workflows/cpp-ros2-tests.yml
  .github/workflows/serialization-tests.yml
Labels: ci

#1589 Fix failing building of tracing tools
  .github/workflows/build-trace-tools.yml
  .github/workflows/ci.yml
  util/tracing/makefile
Labels: tracing, bugfix

#1590 Use of newer actions to reduce number of produced warnings in CI
  .github/actions/prepare-build-env/action.yml
  .github/workflows/c-tests.yml
  .github/workflows/cancel.yml
  .github/workflows/cpp-ros2-tests.yml
  .github/workflows/cpp-tests.yml
  .github/workflows/latest-release.yml
  .github/workflows/lsp-tests.yml
  .github/workflows/py-tests.yml
  .github/workflows/rs-tests.yml
  .github/workflows/serialization-tests.yml
  .github/workflows/ts-tests.yml
  .github/workflows/unit-tests.yml
Labels: ci

#1604 CLI args propagated to federates
  org.lflang/src/org/lflang/TargetProperty.java
  org.lflang/src/org/lflang/federated/generator/FedGenerator.java
Labels: bugfix

#1606 Improved reporting of error that do not relate to a specific file
  org.lflang/src/org/lflang/cli/ReportingUtil.kt
Labels: exclude
