Repository lf-lang/lingua-franca, pull requests merged in 2023-05, with the labels that each got.

#1726 Validator rules to check if target suppports federation or inheritance
  org.lflang.tests/src/org/lflang/tests/compiler/LinguaFrancaValidationTest.java
  org.lflang/src/org/lflang/Target.java
  org.lflang/src/org/lflang/validation/LFValidator.java
Labels: enhancement, validation

#1754 Fix build error in serialization tests in master
  .github/workflows/ts-tests.yml
  org.lflang/src/lib/ts/package.json
  org.lflang/src/org/lflang/generator/ts/TSGenerator.kt
Labels: ci

#1769 Check spotless formatting in CI
  .github/workflows/check-format.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  REQUIREMENTS.md
  org.lflang.tests/src/org/lflang/tests/compiler/RoundTripTests.java
Labels: ci

#1775 Fixed validator check for C generics
  org.lflang/src/org/lflang/validation/LFValidator.java
  test/C/src/generics/TypeCheck.lf
Labels: c, exclude, bugfix

#1735 Updated README for the federate trace visualizer
  util/tracing/visualization/README.md
Labels: docs
