Repository lf-lang/lingua-franca, pull requests merged in 2023-11, with the labels that each got.

#2014 [C] Self struct made available to initializers of state variables, parameters
  core/src/main/java/org/lflang/generator/c/CGenerator.java
  test/C/src/ParentParamsAccessToChildInit.lf
Labels: feature

#2088 Output path specified in JSON used correctly
  cli/base/src/main/java/org/lflang/cli/CliBase.java
Labels: bugfix

#2101 Better placement of line directives
  core/src/main/java/org/lflang/generator/CodeBuilder.java
  core/src/main/java/org/lflang/generator/c/CActionGenerator.java
  core/src/main/java/org/lflang/generator/c/CGenerator.java
  core/src/main/java/org/lflang/generator/c/CMethodGenerator.java
  core/src/main/java/org/lflang/generator/c/CModesGenerator.java
  core/src/main/java/org/lflang/generator/c/CParameterGenerator.java
  core/src/main/java/org/lflang/generator/c/CPortGenerator.java
  core/src/main/java/org/lflang/generator/c/CReactionGenerator.java
  core/src/main/java/org/lflang/generator/c/CStateGenerator.java
  core/src/main/java/org/lflang/generator/c/CWatchdogGenerator.java
  core/src/main/java/org/lflang/generator/python/PythonGenerator.java
  core/src/main/java/org/lflang/generator/python/PythonReactionGenerator.java
Labels: enhancement

#2092 New `--no-source-mapping` switch to disable line directives
  cli/lfc/src/main/java/org/lflang/cli/Lfc.java
  core/src/main/java/org/lflang/generator/CodeBuilder.java
  core/src/main/java/org/lflang/generator/c/CGenerator.java
  core/src/main/java/org/lflang/generator/c/CMethodGenerator.java
  core/src/main/java/org/lflang/generator/c/CParameterGenerator.java
  core/src/main/java/org/lflang/generator/c/CReactionGenerator.java
  core/src/main/java/org/lflang/generator/c/CStateGenerator.java
  core/src/main/java/org/lflang/generator/c/CWatchdogGenerator.java
  core/src/main/java/org/lflang/target/Target.java
  core/src/main/java/org/lflang/target/property/NoSourceMappingProperty.java
Labels: feature

#2107 Check for labels in CI
  .github/workflows/all-misc.yml
  .github/workflows/check-labels.yml
Labels: ci

#2108 Codecov coverage annotations
  codecov.yml
Labels: ci

#2110 Fix undetected `scheduler` and `workers` properties
  core/src/main/java/org/lflang/generator/c/CGenerator.java
Labels: bug

#2109 Labels merge queue fix
  .github/workflows/all-misc.yml
Labels: exclude, ci

#2113 Changes to Codecov configuration
  codecov.yml
Labels: ci
