Repository lf-lang/lingua-franca, pull requests merged in 2023-01, with the labels that each got.

#1498 Correctly report assertion errors and exceptions during code generation
  org.lflang.tests/src/org/lflang/tests/Configurators.java
  org.lflang.tests/src/org/lflang/tests/LFTest.java
  org.lflang.tests/src/org/lflang/tests/RuntimeTest.java
  org.lflang.tests/src/org/lflang/tests/TestBase.java
  org.lflang.tests/src/org/lflang/tests/TestError.java
  org.lflang.tests/src/org/lflang/tests/TestRegistry.java
  org.lflang.tests/src/org/lflang/tests/compiler/RoundTripTests.java
  org.lflang.tests/src/org/lflang/tests/lsp/LspTests.java
  org.lflang.tests/src/org/lflang/tests/runtime/CCppTest.java
  org.lflang.tests/src/org/lflang/tests/runtime/CSchedulerTest.java
  org.lflang.tests/src/org/lflang/tests/runtime/CppRos2Test.java
Labels: testing

#1397 Update README.md
  README.md
Labels: exclude

#1550 Relax deadlines in enclave tests
  test/Cpp/src/enclave/EnclaveBank.lf
  test/Cpp/src/enclave/EnclaveHierarchy.lf
Labels: ci

#1566 Remove use of deprecated reactor-c API in tests
  test/Python/src/docker/FilesPropertyContainerized.lf
  test/Python/src/docker/federated/DistributedStopDecentralizedContainerized.lf
  test/Python/src/federated/CycleDetection.lf
  test/Python/src/federated/DistributedSendClass.lf
  test/Python/src/federated/DistributedStop.lf
  test/Python/src/federated/DistributedStopDecentralized.lf
  test/Python/src/federated/DistributedStopZero.lf
  test/Python/src/federated/HelloDistributed.lf
  test/Python/src/federated/PingPongDistributed.lf
  test/Python/src/federated/StopAtShutdown.lf
  test/Python/src/federated/failing/ClockSync.lf
  test/Python/src/federated/failing/DistributedLoopedActionDecentralized.lf
  test/Python/src/federated/failing/LoopDistributedCentralized.lf
  test/Python/src/federated/failing/LoopDistributedCentralizedPrecedence.lf
  test/Python/src/federated/failing/LoopDistributedDecentralized.lf
  test/Python/src/federated/failing/LoopDistributedDouble.lf
Labels: testing

#1573 Useful error message upon encountering missing runtime sources
  org.lflang/src/org/lflang/util/FileUtil.java
  org.lflang/src/org/lflang/util/TargetResourceNotFoundException.java
Labels: bugfix

#1575 [ts] Bugfix that re-enables the use of custom configuration files
  org.lflang/src/org/lflang/generator/ts/TSGenerator.kt
Labels: bugfix
