Repository lf-lang/lingua-franca, pull requests merged in 2023-03, with the labels that each got.

#1596 Physical connections implemented as AST transformation
  org.lflang.tests/src/org/lflang/tests/compiler/LetInferenceTests.java
  org.lflang/src/org/lflang/ast/DelayedConnectionTransformation.java
  org.lflang/src/org/lflang/generator/c/CGenerator.java
  org.lflang/src/org/lflang/generator/rust/RustGenerator.kt
  org.lflang/src/org/lflang/generator/ts/TSGenerator.kt
  test/C/src/PhysicalConnection.lf
  test/TypeScript/src/PhysicalConnection.lf
Labels: bugfix

#1587 Documentation about LSP tests in `README.md`
  test/README.md
Labels: docs

#1619 Fix for language server "Build and Run" command
  org.lflang/src/org/lflang/FileConfig.java
  org.lflang/src/org/lflang/diagram/lsp/LFLanguageServerExtension.java
  org.lflang/src/org/lflang/generator/c/CGenerator.java
Labels: ide, bugfix

#1628 Simpler cache configuration
  .github/actions/prepare-build-env/action.yml
Labels: ci

#1631 Fix passing of command line options from lfc to the generator
  org.lflang/src/org/lflang/cli/CliBase.java
  org.lflang/src/org/lflang/cli/Lfc.java
  org.lflang/src/org/lflang/cli/Lff.java
Labels: bugfix

#1629 Fix validation of target properties
  org.lflang/src/org/lflang/validation/LFValidator.java
Labels: validation, bugfix

#1643 Fix in validation so that warnings are not reported as errors
  org.lflang/src/org/lflang/generator/GeneratorBase.java
  org.lflang/src/org/lflang/generator/GeneratorUtils.java
Labels: lfc, validation, bugfix

#1655 Fix NPE in lfc error reporting
  org.lflang/src/org/lflang/cli/CliBase.java
Labels: bugfix

#1663 Refactoring of part of the federated package
  org.lflang.tests/src/org/lflang/tests/compiler/TargetConfigTests.java
  org.lflang/src/org/lflang/TargetConfig.java
  org.lflang/src/org/lflang/TargetProperty.java
  org.lflang/src/org/lflang/ast/FormattingUtils.java
  org.lflang/src/org/lflang/federated/extensions/CExtension.java
  org.lflang/src/org/lflang/federated/extensions/CExtensionUtils.java
  org.lflang/src/org/lflang/federated/extensions/FedTargetExtension.java
  org.lflang/src/org/lflang/federated/extensions/FedTargetExtensionFactory.java
  org.lflang/src/org/lflang/federated/extensions/TSExtension.java
  org.lflang/src/org/lflang/federated/generator/FedASTUtils.java
  org.lflang/src/org/lflang/federated/generator/FedEmitter.java
  org.lflang/src/org/lflang/federated/generator/FedFileConfig.java
  org.lflang/src/org/lflang/federated/generator/FedGenerator.java
  org.lflang/src/org/lflang/federated/generator/FedImportEmitter.java
  org.lflang/src/org/lflang/federated/generator/FedMainEmitter.java
  org.lflang/src/org/lflang/federated/generator/FedPreambleEmitter.java
  org.lflang/src/org/lflang/federated/generator/FedReactorEmitter.java
  org.lflang/src/org/lflang/federated/generator/FedTargetConfig.java
  org.lflang/src/org/lflang/federated/generator/FedTargetEmitter.java
  org.lflang/src/org/lflang/federated/generator/FederateInstance.java
  org.lflang/src/org/lflang/federated/launcher/BuildConfig.java
  org.lflang/src/org/lflang/federated/launcher/CBuildConfig.java
  org.lflang/src/org/lflang/federated/launcher/FedLauncherFactory.java
  org.lflang/src/org/lflang/federated/launcher/FedLauncherGenerator.java
  org.lflang/src/org/lflang/federated/launcher/FedPyLauncher.java
  org.lflang/src/org/lflang/federated/launcher/PyBuildConfig.java
  org.lflang/src/org/lflang/federated/launcher/RtiConfig.java
  org.lflang/src/org/lflang/federated/launcher/TsBuildConfig.java
  org.lflang/src/org/lflang/generator/GeneratorUtils.java
  org.lflang/src/org/lflang/generator/MainContext.java
  org.lflang/src/org/lflang/generator/ts/TSGenerator.kt
  org.lflang/src/org/lflang/util/Averager.java
  test/C/src/federated/failing/SimpleFederatedAuthenticated.lf
Labels: refactoring

#1669 Revert "Merge pull request #1660 from lf-lang/klighd-workaround"
  gradle/source-layout.gradle
  org.lflang.tests/build.gradle
  org.lflang/build.gradle
Labels: exclude

#1607 Upstream connection delays now properly handled in the TypeScript federates
  .github/workflows/ci.yml
  .github/workflows/ts-tests.yml
  org.lflang/src/lib/ts/package.json
  org.lflang/src/org/lflang/federated/extensions/TSExtension.java
Labels: typescript, bugfix

#1680 Cleaned up validation tests
  org.lflang.tests/src/org/lflang/tests/compiler/LinguaFrancaValidationTest.java
Labels: exclude, cleanup
