Repository lf-lang/lingua-franca, pull requests merged in 2023-10, with the labels that each got.

#2030 Show reaction names in diagrams
  core/src/main/java/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java
  core/src/main/java/org/lflang/diagram/synthesis/styles/LinguaFrancaShapeExtensions.java
  core/src/main/java/org/lflang/generator/ReactionInstance.java
  test/C/src/verifier/ADASModel.lf
  test/C/src/verifier/AircraftDoor.lf
  test/C/src/verifier/Alarm.lf
  test/C/src/verifier/PingPongVerifier.lf
  test/C/src/verifier/Ring.lf
  test/C/src/verifier/SafeSend.lf
  test/C/src/verifier/TrainDoor.lf
  test/C/src/verifier/UnsafeSend.lf
Labels: enhancement, diagrams

#2040 Fixed trimming of the recorded test output
  core/src/testFixtures/java/org/lflang/tests/LFTest.java
Labels: testing, bugfix

#2038 Fix problems with assignment serialization in diagrams
  core/src/main/java/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java
Labels: diagrams, bugfix

#2068 Updated CI workflow for LSP tests with to remove all g++/clang++ in `PATH`
  .github/workflows/lsp-tests.yml
Labels: ci

#2069 CI updated to include commit SHA in version number when creating nightly build
  .github/workflows/nightly-build.yml
Labels: build system, ci

#2057 Handling of unknown width for multiports
  core/src/main/java/org/lflang/ast/ASTUtils.java
  core/src/main/java/org/lflang/generator/ReactorInstance.java
  core/src/main/java/org/lflang/generator/RuntimeRange.java
  core/src/main/java/org/lflang/generator/SendRange.java
  core/src/main/java/org/lflang/validation/LFValidator.java
Labels: diagrams, bugfix

#2052 Removal of `ulog` from `reactor-ts`, code generator updated to allow this change
  core/src/main/kotlin/org/lflang/generator/ts/TSParameterPreambleGenerator.kt
  core/src/main/resources/lib/ts/package.json
  core/src/main/resources/lib/ts/tsconfig.json
Labels: typescript, refactoring

#2076 Updated .github/workflows/README.md
  .github/workflows/README.md
Labels: docs

#2067 CI testing of `lf-west-template` (for the Zephyr platform)
  .github/actions/setup-zephyr/action.yml
  .github/workflows/c-zephyr-tests.yml
Labels: ci
