Repository lf-lang/lingua-franca, pull requests merged in 2023-08, with the labels that each got.

#1925 Handling cyclic dependencies for TypeScript federated execution
  core/src/main/java/org/lflang/federated/extensions/TSExtension.java
  core/src/main/java/org/lflang/federated/generator/FedASTUtils.java
  core/src/main/java/org/lflang/validation/AttributeSpec.java
  core/src/main/kotlin/org/lflang/generator/ts/TSConstructorGenerator.kt
  core/src/main/kotlin/org/lflang/generator/ts/TSInstanceGenerator.kt
  core/src/main/kotlin/org/lflang/generator/ts/TSReactorGenerator.kt
  core/src/main/resources/lib/ts/package.json
  test/TypeScript/src/federated/DistributedCountPhysicalAfterDelay.lf
  test/TypeScript/src/federated/LoopDistributedCentralized.lf
  test/TypeScript/src/federated/LoopDistributedDouble.lf
  test/TypeScript/src/federated/PingPongDistributed.lf
  test/TypeScript/src/federated/PingPongDistributedPhysical.lf
  test/TypeScript/src/federated/SimpleFederated.lf
  test/TypeScript/src/federated/SpuriousDependency.lf
  test/TypeScript/src/federated/failing/DistributedCountPhysicalAfterDelay.lf
  test/TypeScript/src/federated/failing/LoopDistributedCentralized.lf
  test/TypeScript/src/federated/failing/LoopDistributedDouble.lf
  test/TypeScript/src/federated/failing/PingPongDistributed.lf
Labels: federated

#1933 Support for named and bodyless reactions in C++
  core/src/main/java/org/lflang/Target.java
  core/src/main/kotlin/org/lflang/ast/AstExtensions.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppExtensions.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppReactionGenerator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppReactorGenerator.kt
  test/Cpp/src/HelloBodylessWorld.lf
  test/Cpp/src/hello_bodyless_world.cc
  test/Cpp/src/hello_bodyless_world.cmake
Labels: enhancement

#1960 Handling of caching across runs using `gradle-build-action`
  .github/actions/prepare-build-env/action.yml
Labels: ci

#1974 New job for building `epoch` in CI
  .github/workflows/build.yml
Labels: testing

#1976 Action for setting up francabot
  .github/actions/setup-francabot/action.yml
Labels: ci
