Repository lf-lang/lingua-franca, pull requests merged in 2023-09, with the labels that each got.

#1983 Fixed path issue in generated `docker-compose.yml` for federations
  core/src/main/java/org/lflang/generator/DockerGenerator.java
Labels: federated, docker, bugfix

#1988 Gradlew not longer used to run dev version of lf cli tools
  .github/scripts/test-lfc.sh
  .github/scripts/test-lfd.sh
  .github/scripts/test-lff.sh
  .github/workflows/cli-tests.yml
  bin/lfc-dev
  bin/lfc-dev.ps1
  bin/lfd-dev
  bin/lfd-dev.ps1
  bin/lff-dev
  bin/lff-dev.ps1
  util/scripts/launch.ps1
  util/scripts/launch.sh
Labels: refactoring

#1991 Cleanup of latest-release workflow
  .github/actions/latest-release/action.yml
  .github/workflows/latest-release.yml
Labels: ci

#1979 Minor fixes for C++ tests
  test/Cpp/src/ArrayScale.lf
  test/Cpp/src/enclave/EnclaveMultiportToPort.lf
  test/Cpp/src/enclave/EnclaveMultiportToPort2.lf
  test/Cpp/src/multiport/MultiportFromBankHierarchyAfter.lf
  test/Cpp/src/multiport/MultiportFromHierarchy.lf
  test/Cpp/src/multiport/MultiportIn.lf
  test/Cpp/src/multiport/MultiportToMultiportArray.lf
  test/Cpp/src/multiport/MultiportToPort.lf
Labels: testing

#1953 Fix for unconnected multiport and bank reactor bug
  core/src/main/java/org/lflang/generator/c/CTriggerObjectsGenerator.java
  test/C/src/multiport/MultiBank_UnconnectedOutput_Test.lf
  test/C/src/multiport/MultiPort_MultiBankTest_UnconnectedOutput_Test.lf
Labels: c, bugfix

#2018 Stabilized LSP diagram genenation and added default expansion option
  core/src/main/java/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java
  lsp/build.gradle
Labels: diagrams, bugfix

#2020 Avoid null pointer exception in diagrams with bodyless reactions
  core/src/main/java/org/lflang/diagram/synthesis/styles/LinguaFrancaShapeExtensions.java
Labels: diagrams, bugfix

#2019 Removed "Reaction level" diagram synthesis option
  core/src/main/java/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java
  core/src/main/java/org/lflang/diagram/synthesis/styles/LinguaFrancaShapeExtensions.java
Labels: diagrams, bugfix

#2021 Removed stray print statement
  core/src/main/java/org/lflang/AttributeUtils.java
Labels: cleanup

#2003 Bracket list expression for initialization without escaping
  .github/workflows/build.yml
  core/src/main/java/org/lflang/LinguaFranca.xtext
  core/src/main/java/org/lflang/Target.java
  core/src/main/java/org/lflang/ast/IsEqual.java
  core/src/main/java/org/lflang/ast/ToLf.java
  core/src/main/java/org/lflang/ast/ToText.java
  core/src/main/java/org/lflang/generator/LfExpressionVisitor.java
  core/src/main/java/org/lflang/generator/TargetTypes.java
  core/src/main/java/org/lflang/validation/LFValidator.java
  test/Python/src/ArrayAsParameter.lf
  test/Python/src/modal_models/util/TraceTesting.lf
  test/Rust/src/ArrayAsParameter.lf
  test/TypeScript/src/ArrayAsParameter.lf
  test/TypeScript/src/MovingAverage.lf
Labels: feature

#2031 Fixed error reporting in the verifier
  core/src/main/java/org/lflang/analyses/uclid/UclidRunner.java
  core/src/main/java/org/lflang/generator/GeneratorBase.java
  core/src/main/java/org/lflang/generator/LFGenerator.java
Labels: testing, bugfix
