Repository lf-lang/lingua-franca, pull requests merged in 2023-06, with the labels that each got.

#1776 `SimpleFederatedAuthenticated.lf` test passing
  test/C/src/federated/SimpleFederatedAuthenticated.lf
Labels: testing

#1752 Federated launch script to error when RTI is missing
  .github/workflows/py-tests.yml
  .github/workflows/serialization-tests.yml
  .github/workflows/ts-tests.yml
  core/src/main/java/org/lflang/TargetProperty.java
  core/src/main/java/org/lflang/federated/extensions/TSExtension.java
  core/src/main/java/org/lflang/federated/generator/FedTargetConfig.java
  core/src/main/java/org/lflang/federated/launcher/FedLauncherGenerator.java
  core/src/main/kotlin/org/lflang/generator/ts/TSConstructorGenerator.kt
  core/src/testFixtures/java/org/lflang/tests/LFTest.java
  core/src/testFixtures/java/org/lflang/tests/TestBase.java
  test/Python/src/docker/FilesPropertyContainerized.lf
  test/Python/src/docker/federated/DistributedStopDecentralizedContainerized.lf
  test/Python/src/federated/CycleDetection.lf
  test/Python/src/federated/DistributedCountDecentralizedLate.lf
  test/Python/src/federated/DistributedCountDecentralizedLateHierarchy.lf
  test/Python/src/federated/DistributedSendClass.lf
  test/Python/src/federated/DistributedStop.lf
  test/Python/src/federated/DistributedStopDecentralized.lf
  test/Python/src/federated/DistributedStopZero.lf
  test/Python/src/federated/HelloDistributed.lf
  test/Python/src/federated/PingPongDistributed.lf
  test/Python/src/federated/StopAtShutdown.lf
  test/Python/src/include/hello.py
  test/TypeScript/src/federated/failing/DistributedCountPhysicalAfterDelay.lf
  test/TypeScript/src/federated/failing/LoopDistributedCentralized.lf
  test/TypeScript/src/federated/failing/LoopDistributedDouble.lf
  test/TypeScript/src/federated/failing/PingPongDistributed.lf
  test/TypeScript/src/federated/failing/PingPongDistributedPhysical.lf
  test/TypeScript/src/federated/failing/SimpleFederated.lf
  test/TypeScript/src/lib/TestCount.lf
Labels: bugfix

#1816 Fix bugs in name mangling
  .github/workflows/check-diff.yml
  core/src/integrationTest/java/org/lflang/tests/RuntimeTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CZephyrTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CppTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/PythonTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/RustTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/TypeScriptTest.java
  core/src/main/java/org/lflang/generator/ReactorInstance.java
  core/src/main/java/org/lflang/generator/c/CGenerator.java
  core/src/main/java/org/lflang/generator/c/TypeParameterizedReactor.java
  core/src/main/java/org/lflang/validation/LFValidator.java
  core/src/testFixtures/java/org/lflang/tests/TestBase.java
  core/src/testFixtures/java/org/lflang/tests/TestRegistry.java
Labels: exclude

#1821 Changes to workflow dispatch
  .github/workflows/all-misc.yml
  .github/workflows/all-targets.yml
  .github/workflows/only-c.yml
  .github/workflows/only-cpp.yml
  .github/workflows/only-py.yml
  .github/workflows/only-rs.yml
  .github/workflows/only-ts.yml
Labels: exclude, ci

#1822 New `--check` flag for `lff`
  cli/base/src/main/kotlin/org/lflang/cli/ReportingUtil.kt
  cli/lff/src/main/java/org/lflang/cli/Lff.java
  cli/lff/src/test/java/org/lflang/cli/LffCliTest.java
  core/src/main/java/org/lflang/util/FileUtil.java
Labels: enhancement

#1827 Fix error in programs with no main reactor
  core/src/main/java/org/lflang/ast/ASTUtils.java
Labels: c, cpp, exclude, bugfix

#1829 Check to avoid repeated CI runs
  .github/scripts/check-diff.sh
  .github/workflows/all-misc.yml
  .github/workflows/all-targets.yml
  .github/workflows/check-diff.yml
  .github/workflows/only-c.yml
  .github/workflows/only-cpp.yml
  .github/workflows/only-rs.yml
  .github/workflows/only-ts.yml
Labels: ci

#1807 Adjustable port sides for reactors
  core/src/main/java/org/lflang/AttributeUtils.java
  core/src/main/java/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java
  core/src/main/java/org/lflang/diagram/synthesis/SynthesisRegistration.java
  core/src/main/java/org/lflang/diagram/synthesis/postprocessor/ReactionPortAdjustment.java
  core/src/main/java/org/lflang/diagram/synthesis/postprocessor/ReactorPortAdjustment.java
  core/src/main/java/org/lflang/diagram/synthesis/styles/LinguaFrancaShapeExtensions.java
  core/src/main/java/org/lflang/validation/AttributeSpec.java
Labels: enhancement, diagrams

#1836 Fedsd compatibility with pandas 2.0
  util/tracing/visualization/fedsd.py
Labels: tracing, bugfix

#1844 Adjustments for running the LF compiler in Epoch
  cli/base/src/main/java/org/lflang/cli/CliBase.java
  cli/base/src/main/java/org/lflang/cli/StandaloneIssueAcceptor.java
  core/src/main/java/org/lflang/ModelInfo.java
  core/src/main/java/org/lflang/TargetProperty.java
  core/src/main/java/org/lflang/federated/generator/FedTargetConfig.java
  core/src/main/java/org/lflang/generator/LanguageServerErrorReporter.java
  core/src/main/java/org/lflang/generator/c/CReactorHeaderFileGenerator.java
  core/src/main/java/org/lflang/util/FileUtil.java
Labels: epoch

#1858 Cleanup gradle config
  core/build.gradle
  core/src/main/java/org/lflang/GenerateLinguaFranca.mwe2
Labels: gradle, exclude
