Repository lf-lang/lingua-franca, pull requests merged in 2024-01, with the labels that each got.

#2144 Ability to specify rti image for dockerized federated programs
  core/src/main/java/org/lflang/federated/generator/FedGenerator.java
  core/src/main/java/org/lflang/generator/c/CGenerator.java
  core/src/main/java/org/lflang/generator/docker/CDockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/DockerComposeGenerator.java
  core/src/main/java/org/lflang/generator/docker/DockerData.java
  core/src/main/java/org/lflang/generator/docker/DockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/FedDockerComposeGenerator.java
  core/src/main/java/org/lflang/generator/docker/PythonDockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/RtiDockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/TSDockerGenerator.java
  core/src/main/java/org/lflang/generator/python/PythonGenerator.java
  core/src/main/java/org/lflang/target/property/DockerProperty.java
  core/src/main/kotlin/org/lflang/generator/ts/TSGenerator.kt
  test/C/src/docker/federated/DistributedCountContainerized.lf
  test/C/src/docker/federated/DistributedDoublePortContainerized.lf
  test/C/src/docker/federated/DistributedMultiportContainerized.lf
  test/C/src/docker/federated/DistributedStopDecentralizedContainerized.lf
  test/TypeScript/src/docker/federated/DistributedCountContainerized.lf
Labels: feature

#2145 Parallel compilation disabled to avoid triggering deadlock in concurrent invocations of CMake
  core/src/main/java/org/lflang/federated/generator/FedGenerator.java
Labels: compiler, federated, bugfix

#2136 String literal allowed as property name
  core/src/main/java/org/lflang/LinguaFranca.xtext
  core/src/test/java/org/lflang/tests/LFParsingTest.java
Labels: enhancement

#2151 Python docker parent image fixed at version `3.10`
  core/src/main/java/org/lflang/generator/docker/PythonDockerGenerator.java
Labels: python, docker, bugfix

#2112 Fix for cycle detection issue
  core/src/main/java/org/lflang/federated/generator/FedASTUtils.java
  core/src/main/java/org/lflang/generator/PortInstance.java
  test/C/src/PhysicalConnectionCycle.lf
Labels: bugfix

#2157 Fixed `hashCode()` implementation in `TimeValue` class
  core/src/main/java/org/lflang/TimeValue.java
  test/C/src/federated/MultipleSTP.lf
Labels: bugfix

#2158 Removal of image-specific commands in case base image is specified
  core/src/main/java/org/lflang/generator/docker/CDockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/DockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/PythonDockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/RtiDockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/TSDockerGenerator.java
  core/src/main/java/org/lflang/target/property/DockerProperty.java
Labels: bugfix

#2160 Fix some zephyr build issues
  core/src/main/java/org/lflang/generator/c/CCmakeGenerator.java
Labels: bugfix, zephyr

#2147 Fix for #2087
  core/src/main/java/org/lflang/validation/LFNamesAreUniqueValidationHelper.java
  core/src/test/java/org/lflang/tests/compiler/LinguaFrancaValidationTest.java
Labels: bugfix

#2163 Coverage threshold changed to avoid transient failures being reported …
  codecov.yml
Labels: ci

#2164 Fixed parameter forwarding for non-trivial types in C++
  core/src/main/kotlin/org/lflang/generator/cpp/CppReactorGenerator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppTypes.kt
  test/Cpp/src/ParameterHierarchy.lf
Labels: bugfix

#2165 Fixed generation of preambles for unused imports
  core/src/main/kotlin/org/lflang/generator/cpp/CppGenerator.kt
  test/Cpp/src/PreambleImport.lf
  test/Cpp/src/PreambleTest.lf
Labels: bugfix

#2169 Use login shell so ~/.bash_profile is sourced
  core/src/main/java/org/lflang/federated/launcher/FedLauncherGenerator.java
Labels: enhancement, federated

#2173 Use local rti in DistributedStopDecentralizedContainerized.lf
  test/C/src/docker/federated/DistributedStopDecentralizedContainerized.lf
Labels: testing, exclude
