Repository lf-lang/lingua-franca, pull requests merged in 2024-06, with the labels that each got.

#2306 Bumped gradle version to 8.8
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: build system, exclude

#2308 Bumped the google-java-format version to 1.22.0
  cli/lfc/src/main/java/org/lflang/cli/Lfc.java
  cli/lfc/src/test/java/org/lflang/cli/LfcCliTest.java
  cli/lfd/src/test/java/org/lflang/cli/LfdCliTest.java
  cli/lff/src/test/java/org/lflang/cli/LffCliTest.java
  core/src/integrationTest/java/org/lflang/tests/lsp/ErrorInserter.java
  core/src/integrationTest/java/org/lflang/tests/lsp/LspTests.java
  core/src/main/java/org/lflang/InferredType.java
  core/src/main/java/org/lflang/TimeValue.java
  core/src/main/java/org/lflang/ast/DelayedConnectionTransformation.java
  core/src/main/java/org/lflang/ast/FormattingUtil.java
  core/src/main/java/org/lflang/diagram/synthesis/util/LayoutPostProcessing.java
  core/src/main/java/org/lflang/federated/extensions/CExtension.java
  core/src/main/java/org/lflang/federated/extensions/CExtensionUtils.java
  core/src/main/java/org/lflang/federated/extensions/PythonExtension.java
  core/src/main/java/org/lflang/federated/extensions/TSExtension.java
  core/src/main/java/org/lflang/federated/generator/FedMainEmitter.java
  core/src/main/java/org/lflang/federated/generator/FedPreambleEmitter.java
  core/src/main/java/org/lflang/federated/serialization/FedROS2CPPSerialization.java
  core/src/main/java/org/lflang/generator/CodeMap.java
  core/src/main/java/org/lflang/generator/GenerationException.java
  core/src/main/java/org/lflang/generator/HumanReadableReportingStrategy.java
  core/src/main/java/org/lflang/generator/LanguageServerMessageReporter.java
  core/src/main/java/org/lflang/generator/MainContext.java
  core/src/main/java/org/lflang/generator/Range.java
  core/src/main/java/org/lflang/generator/ReactionInstance.java
  core/src/main/java/org/lflang/generator/c/CCmakeGenerator.java
  core/src/main/java/org/lflang/generator/c/CGenerator.java
  core/src/main/java/org/lflang/generator/c/CMainFunctionGenerator.java
  core/src/main/java/org/lflang/generator/c/CMixedRadixGenerator.java
  core/src/main/java/org/lflang/generator/c/CPreambleGenerator.java
  core/src/main/java/org/lflang/generator/c/CReactionGenerator.java
  core/src/main/java/org/lflang/generator/c/CReactorHeaderFileGenerator.java
  core/src/main/java/org/lflang/generator/c/TypeParameterizedReactor.java
  core/src/main/java/org/lflang/generator/docker/CDockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/DockerComposeGenerator.java
  core/src/main/java/org/lflang/generator/docker/DockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/FedDockerComposeGenerator.java
  core/src/main/java/org/lflang/generator/docker/PythonDockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/TSDockerGenerator.java
  core/src/main/java/org/lflang/generator/python/PythonGenerator.java
  core/src/main/java/org/lflang/generator/python/PythonValidator.java
  core/src/main/java/org/lflang/target/Target.java
  core/src/main/java/org/lflang/target/property/ClockSyncOptionsProperty.java
  core/src/main/java/org/lflang/target/property/type/ClockSyncModeType.java
  core/src/main/java/org/lflang/util/FileUtil.java
  core/src/main/java/org/lflang/util/LFCommand.java
  core/src/main/java/org/lflang/validation/ValidatorMessageReporter.java
  core/src/test/java/org/lflang/tests/compiler/EquivalenceUnitTests.java
  core/src/test/java/org/lflang/tests/compiler/FormattingUnitTests.java
  core/src/test/java/org/lflang/tests/compiler/LinguaFrancaASTUtilsTest.java
  core/src/test/java/org/lflang/tests/compiler/LinguaFrancaDependencyAnalysisTest.java
  core/src/test/java/org/lflang/tests/compiler/LinguaFrancaParsingTest.java
  core/src/test/java/org/lflang/tests/compiler/LinguaFrancaScopingTest.java
  core/src/test/java/org/lflang/tests/compiler/LinguaFrancaValidationTest.java
  core/src/testFixtures/java/org/lflang/tests/TestBase.java
  core/src/testFixtures/java/org/lflang/tests/TestRegistry.java
  gradle.properties
Labels: exclude

#2311 Updated CONTRIBUTING.md to focus on repository-specific guidelines
  CONTRIBUTING.md
Labels: exclude

#2178 Rp2040 multithreaded target support
  core/src/main/java/org/lflang/generator/c/CCmakeGenerator.java
  core/src/main/java/org/lflang/target/property/PlatformProperty.java
  core/src/main/java/org/lflang/target/property/type/PlatformType.java
Labels: feature

#2312 No more support for Python 3.9
  core/src/main/java/org/lflang/generator/python/PythonGenerator.java
Labels: bugfix

#2321 Stop removing GCC on MacOS in CI
  .github/workflows/lsp-tests.yml
Labels: build system, exclude, ci

#2322 Docker support for C++ target
  core/src/main/java/org/lflang/generator/docker/DockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/PythonDockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/TSDockerGenerator.java
  core/src/main/java/org/lflang/target/Target.java
  core/src/main/kotlin/org/lflang/generator/cpp/CppGenerator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppPlatformGenerator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppRos2Generator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppRos2PackageGenerator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppStandaloneCmakeGenerator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppStandaloneGenerator.kt
  test/Cpp/src/docker/HelloWorldContainerized.lf
Labels: feature

#2234 Improved support for Docker
  .github/workflows/build.yml
  core/build.gradle
  core/src/main/java/org/lflang/analyses/uclid/UclidGenerator.java
  core/src/main/java/org/lflang/federated/generator/FedGenerator.java
  core/src/main/java/org/lflang/generator/GeneratorBase.java
  core/src/main/java/org/lflang/generator/c/CGenerator.java
  core/src/main/java/org/lflang/generator/docker/CDockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/DockerComposeGenerator.java
  core/src/main/java/org/lflang/generator/docker/DockerData.java
  core/src/main/java/org/lflang/generator/docker/DockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/FedDockerComposeGenerator.java
  core/src/main/java/org/lflang/generator/docker/PythonDockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/RtiDockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/TSDockerGenerator.java
  core/src/main/java/org/lflang/target/Target.java
  core/src/main/java/org/lflang/target/TargetConfig.java
  core/src/main/java/org/lflang/target/property/DockerProperty.java
  core/src/main/kotlin/org/lflang/generator/cpp/CppGenerator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppPlatformGenerator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppRos2Generator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppRos2PackageGenerator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppStandaloneCmakeGenerator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppStandaloneGenerator.kt
  core/src/main/kotlin/org/lflang/generator/rust/RustGenerator.kt
  core/src/main/kotlin/org/lflang/generator/ts/TSGenerator.kt
  core/src/test/java/org/lflang/tests/compiler/LinguaFrancaValidationTest.java
  gradle.properties
  test/C/src/docker/federated/DockerOptions.lf
  test/C/src/docker/federated/EscapedScriptName.lf
  test/C/src/docker/federated/bar.sh
  test/C/src/docker/federated/baz.sh
  test/C/src/docker/federated/cmake-check-environment-variable.cmake
  test/C/src/docker/federated/foo ish.sh
  test/C/src/docker/federated/foo.sh
  test/Cpp/src/docker/HelloWorldContainerized.lf
Labels: enhancement

#2328 Fixed docker testing
  core/src/integrationTest/java/org/lflang/tests/runtime/CppTest.java
  core/src/main/java/org/lflang/generator/docker/DockerComposeGenerator.java
  core/src/main/kotlin/org/lflang/generator/cpp/CppPlatformGenerator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppRos2Generator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppStandaloneGenerator.kt
  core/src/main/kotlin/org/lflang/generator/ts/TSFileConfig.kt
  core/src/testFixtures/java/org/lflang/tests/TestBase.java
Labels: testing, docker

#2327 Make files available in Docker runner image
  core/src/main/java/org/lflang/generator/docker/DockerGenerator.java
  test/C/src/docker/RuntimeFilesPropertyContainerized.lf
Labels: c, docker, bugfix

#2330 Fixed docker compose script so that it fails if any container fails
  core/src/main/java/org/lflang/generator/docker/DockerComposeGenerator.java
Labels: docker, exclude

#2335 Fixed docker generation for images that use /bin/sh
  core/src/main/java/org/lflang/generator/docker/DockerGenerator.java
Labels: enhancement, docker

#2337 Safer directory creation in Docker container
  core/src/main/java/org/lflang/generator/docker/DockerGenerator.java
Labels: enhancement

#2232 Bugfixes in handling of target properties across imports
  core/src/main/java/org/lflang/federated/generator/FederateTargetConfig.java
  core/src/main/java/org/lflang/generator/GeneratorBase.java
  core/src/main/java/org/lflang/generator/GeneratorUtils.java
  core/src/main/java/org/lflang/generator/LFResource.java
  core/src/main/java/org/lflang/generator/c/CGenerator.java
  core/src/main/java/org/lflang/target/TargetConfig.java
  core/src/main/java/org/lflang/target/property/CmakeIncludeProperty.java
  core/src/main/java/org/lflang/target/property/FileListProperty.java
  core/src/main/java/org/lflang/target/property/TargetProperty.java
  core/src/main/java/org/lflang/util/FileUtil.java
  test/C/src/target/ImportedCMakeInclude.lf
Labels: federated, bugfix
