Repository lf-lang/lingua-franca, pull requests merged in 2024-10, with the labels that each got.

#2421 Native `forever` and `never` time literal
  core/src/main/java/org/lflang/LinguaFranca.xtext
  core/src/main/java/org/lflang/TimeValue.java
  core/src/main/java/org/lflang/ast/ASTUtils.java
  core/src/main/java/org/lflang/generator/TargetTypes.java
  core/src/main/java/org/lflang/validation/LFValidator.java
  test/C/src/LastTimeDefer.lf
  test/C/src/LastTimeDrop.lf
  test/C/src/LastTimeReplace.lf
  test/C/src/modal_models/BanksCount3ModesComplex.lf
  test/C/src/modal_models/ModalNestedReactions.lf
  test/Python/src/federated/Dataflow.lf
  test/Python/src/modal_models/BanksCount3ModesComplex.lf
  test/Python/src/modal_models/ModalNestedReactions.lf
Labels: feature

#2404 Angular bracket imports for reusable reactor modules
  .gitignore
  core/src/main/java/org/lflang/LFResourceDescriptionStrategy.java
  core/src/main/java/org/lflang/LinguaFranca.xtext
  core/src/main/java/org/lflang/ast/IsEqual.java
  core/src/main/java/org/lflang/ast/ToLf.java
  core/src/main/java/org/lflang/ast/ToSExpr.java
  core/src/main/java/org/lflang/federated/generator/FedImportEmitter.java
  core/src/main/java/org/lflang/scoping/LFGlobalScopeProvider.java
  core/src/main/java/org/lflang/scoping/LFScopeProviderImpl.java
  core/src/main/java/org/lflang/util/ImportUtil.java
  test/Python/build/lfc_include/library-test/src/lib/Import.lf
  test/Python/src/LingoFederatedImport.lf
  test/Python/src/lingo_imports/FederatedTestImportPackages.lf
  test/Python/src/lingo_imports/TestImportPackages.lf
Labels: feature

#2427 File extension of TypeScript launch script adjusted on Windows
  core/src/main/kotlin/org/lflang/generator/ts/TSFileConfig.kt
  core/src/main/kotlin/org/lflang/generator/ts/TSGenerator.kt
Labels: bugfix

#2428 Do not segfault when Python reactions fail.
  core/src/main/java/org/lflang/generator/python/PythonReactionGenerator.java
Labels: bugfix

#2430 Unhook LSP tests from CI
  .github/workflows/all-misc.yml
  .github/workflows/lsp-tests.yml
Labels: ci

#2383 Support for Patmos platform
  .github/actions/setup-patmos/action.yml
  .github/workflows/c-embedded.yml
  .github/workflows/c-patmos-tests.yml
  .github/workflows/rti-docker.yml
  core/src/integrationTest/java/org/lflang/tests/RuntimeTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CCppTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CPatmosTest.java
  core/src/main/java/org/lflang/generator/c/CCmakeGenerator.java
  core/src/main/java/org/lflang/target/property/type/PlatformType.java
  core/src/testFixtures/java/org/lflang/tests/Configurators.java
  core/src/testFixtures/java/org/lflang/tests/TestRegistry.java
  test/C/src/patmos/HelloPatmos.lf
Labels: feature
