Repository lf-lang/lingua-franca, pull requests merged in 2024-05, with the labels that each got.

#2272 Fix for validation of target properties dictionaries
  core/src/main/java/org/lflang/target/property/type/DictionaryType.java
Labels: validation, bugfix

#2277 Search for imported reactors to include reactors instantiated in modes
  core/src/main/java/org/lflang/federated/generator/FederateInstance.java
  test/C/src/federated/ImportsInModes.lf
Labels: c, federated, bugfix

#2267 Set annotated layout options for modes.
  core/src/main/java/org/lflang/diagram/synthesis/util/ModeDiagrams.java
Labels: bugfix

#2284 Fixed code generation for nested generic reactor instances
  core/src/main/kotlin/org/lflang/generator/cpp/CppInstanceGenerator.kt
  test/Cpp/src/target/GenericComposition.lf
Labels: bugfix

#2285 Code-generator changes required for reactor-c clock-sync fix
  core/src/main/java/org/lflang/federated/extensions/CExtensionUtils.java
  core/src/main/java/org/lflang/target/property/type/ClockSyncModeType.java
Labels: c, federated, bugfix

#2292 Support for Python 3.9.x
  core/src/main/java/org/lflang/generator/python/PythonGenerator.java
Labels: enhancement, python

#2301 Bumped klighd version to 3.0.2.v20240507
  gradle.properties
Labels: upgrade
