Repository lf-lang/lingua-franca, pull requests merged in 2024-02, with the labels that each got.

#2176 [CI] codecov-action bumped to v4.0.0
  .github/actions/report-code-coverage/action.yml
Labels: ci

#2174 Fixed path conversion on Windows
  core/src/main/java/org/lflang/generator/CodeMap.java
Labels: bugfix

#2180 Reduced scope for conflicting main reactors check
  core/src/main/java/org/lflang/MainConflictChecker.java
Labels: bugfix

#2182 Have colorized outputs from C/Cpp compilers as default
  core/src/main/java/org/lflang/generator/c/CCmakeGenerator.java
  core/src/main/kotlin/org/lflang/generator/cpp/CppStandaloneCmakeGenerator.kt
Labels: enhancement, c, cpp, cmake

#2186 Escape special characters in type arguments.
  core/src/main/java/org/lflang/generator/c/TypeParameterizedReactor.java
  test/C/src/target/TypeSanitization.lf
Labels: c, bugfix

#2175 CI for macOS and Windows only ran periodically, not continuously
  .github/workflows/all-misc.yml
  .github/workflows/all-targets.yml
  .github/workflows/non-target-specific-extended.yml
  .github/workflows/only-c.yml
  .github/workflows/only-cpp.yml
  .github/workflows/only-py.yml
  .github/workflows/only-rs.yml
  .github/workflows/only-ts.yml
Labels: ci

#2194 Parameterized default branch in check-diff script
  .github/scripts/check-diff.sh
  .github/workflows/check-diff.yml
Labels: ci

#2201 Fixed clang warnings in generated C++ code
  core/src/main/kotlin/org/lflang/generator/cpp/CppAssembleMethodGenerator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppParameterGenerator.kt
  core/src/main/kotlin/org/lflang/generator/cpp/CppReactorGenerator.kt
  test/Cpp/src/multiport/MultiportToMultiportAfterParameterized.lf
Labels: enhancement

#2215 Fix in CDockerGenerator.java
  core/src/main/java/org/lflang/generator/docker/CDockerGenerator.java
Labels: c, docker, exclude

#2217 Report unsupported target properties as errors
  core/src/main/java/org/lflang/target/TargetConfig.java
  core/src/test/java/org/lflang/tests/compiler/LinguaFrancaValidationTest.java
  test/C/src/concurrent/Threaded.lf
  test/C/src/concurrent/ThreadedMultiport.lf
  test/C/src/concurrent/ThreadedThreaded.lf
  test/C/src/concurrent/Tracing.lf
  test/C/src/federated/LoopDistributedCentralizedPhysicalAction.lf
  test/C/src/federated/LoopDistributedCentralizedPrecedence.lf
  test/C/src/federated/LoopDistributedCentralizedPrecedenceHierarchy.lf
Labels: enhancement
