Repository lf-lang/lingua-franca, pull requests merged in 2024-03, with the labels that each got.

#2231 Fix failing Zephyr tests in CI
  .github/scripts/run-zephyr-tests.sh
Labels: ci, zephyr

#2230 Fixed null pointer exception in message reporting
  core/src/main/java/org/lflang/MessageReporterBase.java
Labels: bugfix

#2222 Fixed code generation for connections involving enclave banks with multiports
  core/src/main/kotlin/org/lflang/generator/cpp/CppAssembleMethodGenerator.kt
  test/Cpp/src/enclave/EnclaveCommunicationMultiportBankToMultiportBank.lf
  test/Cpp/src/enclave/EnclaveCommunicationMultiportBankToMultiportBankInterleave.lf
Labels: bugfix

#2236 Add -f flag to rm between zephyr test runs
  .github/workflows/c-zephyr-tests.yml
Labels: ci, bugfix

#2240 Python tests to use an rti that matches the reactor-c checkout
  .github/workflows/py-tests.yml
Labels: ci

#2247 Fixed clean building federated programs
  core/src/main/java/org/lflang/generator/GeneratorBase.java
  core/src/main/java/org/lflang/generator/LFGeneratorContext.java
  core/src/main/java/org/lflang/generator/SubContext.java
Labels: bugfix
