Repository lf-lang/lingua-franca, pull requests merged in 2024-08, with the labels that each got.

#2386 Disable most Zephyr tests
  .github/workflows/c-zephyr-tests.yml
Labels: exclude

#2391 Update latest rti image for released versions
  .github/workflows/rti-docker.yml
Labels: ci

#2392 Allow rti-docker workflow to be triggered on workflow_call
  .github/workflows/rti-docker.yml
Labels: exclude, ci

#2393 Matching image digest between `latest` tag and latest release tag of `rti` image on DockerHub
  .github/actions/push-rti-docker/action.yml
  .github/workflows/rti-docker.yml
Labels: ci

#2396 Watchdog tests marked as failing
  test/C/src/concurrent/failing/Watchdog.lf
  test/C/src/concurrent/failing/WatchdogAction.lf
  test/C/src/concurrent/failing/WatchdogMultiple.lf
  test/C/src/concurrent/failing/WatchdogMutex.lf
  test/C/src/concurrent/failing/WatchdogRestartTerminated.lf
Labels: exclude

#2324 Colored highlighting of selected diagram edges
  core/src/main/java/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java
  core/src/main/java/org/lflang/diagram/synthesis/styles/LinguaFrancaStyleExtensions.java
Labels: diagrams, feature

#2402 No longer attempt to push RTI Image to Docker Hub when CI is run in fork
  .github/workflows/rti-docker.yml
Labels: enhancement, ci

#2370 Changes in the Lingua Franca Language Server to support improvements in the VSCode extension
  lsp/src/main/java/org/lflang/diagram/lsp/LFLanguageClient.java
  lsp/src/main/java/org/lflang/diagram/lsp/LFLanguageServerExtension.java
  lsp/src/main/java/org/lflang/diagram/lsp/LanguageDiagramServer.java
  lsp/src/main/java/org/lflang/diagram/lsp/LibraryFile.java
  lsp/src/main/java/org/lflang/diagram/lsp/NodePosition.java
  lsp/src/main/java/org/lflang/diagram/lsp/ReactorNode.java
Labels: enhancement
