Repository lf-lang/lingua-franca, pull requests merged in 2024-04, with the labels that each got.

#2251 Docker compose also create bin directory if not present
  core/src/main/java/org/lflang/generator/docker/DockerComposeGenerator.java
Labels: docker, bugfix

#2255 Fix rust setup action in CI
  .github/workflows/lsp-tests.yml
  .github/workflows/rs-tests.yml
  core/src/main/kotlin/org/lflang/generator/rust/RustMainFileEmitter.kt
Labels: exclude, ci

#2253 Replacement of `javax.inject` with `com.google.inject`
  core/src/main/java/org/lflang/diagram/synthesis/AbstractSynthesisExtensions.java
  core/src/main/java/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java
  core/src/main/java/org/lflang/diagram/synthesis/postprocessor/ReactorPortAdjustment.java
  core/src/main/java/org/lflang/diagram/synthesis/styles/LinguaFrancaShapeExtensions.java
  core/src/main/java/org/lflang/diagram/synthesis/styles/LinguaFrancaStyleExtensions.java
Labels: refactoring

#2260 IntelliJ run config to start the LS
  .run/LanguageDiagramServer.run.xml
Labels: enhancement, build system

#2264 Xtext bumped to 3.34.0
  core/src/test/java/org/lflang/tests/compiler/LetInferenceTests.java
  core/src/test/java/org/lflang/tests/compiler/LinguaFrancaASTUtilsTest.java
  gradle.properties
Labels: upgrade

#2270 Fix NPE bug for instance in mode
  core/src/main/java/org/lflang/graph/InstantiationGraph.java
  test/C/src/ImportInstanceInMode.lf
  test/C/src/lib/InstanceInMode.lf
Labels: bugfix
