Repository lf-lang/lingua-franca, pull requests merged in 2025-08, with the labels that each got.

#2534 Enhancing Patmos's action.yml
  .github/actions/setup-patmos/action.yml
  .github/workflows/c-embedded.yml
Labels: ci

#2542 Faster tests and disable enclave tests on Windows
  .github/workflows/c-tests.yml
  core/src/integrationTest/java/org/lflang/tests/runtime/CTest.java
  core/src/main/java/org/lflang/validation/LFValidator.java
  core/src/testFixtures/java/org/lflang/tests/TestBase.java
  test/C/src/enclave/ContainedEnclaveToParent.lf
  test/C/src/enclave/DelayedConnection.lf
  test/C/src/enclave/EnclaveBlockingReaction.lf
  test/C/src/enclave/EnclaveRequestStop.lf
  test/C/src/enclave/EnclaveToParent.lf
  test/C/src/enclave/EnclaveTracing.lf
  test/C/src/enclave/EnclavedTokenConnection.lf
  test/C/src/enclave/NonCommunicating.lf
  test/C/src/enclave/NumberOfWorkers.lf
  test/C/src/enclave/ParentToContainedEnclave.lf
  test/C/src/enclave/PhysicalEnclavedConnection.lf
  test/C/src/enclave/SimpleConnection.lf
  test/C/src/enclave/SimpleCoordination.lf
  test/C/src/enclave/UnconnectedEnclave.lf
  test/C/src/enclave/WithParameters.lf
  test/C/src/enclave/lib/SimpleEnclave.lf
  test/C/src/federated/failing/DistributedLogicalActionUpstreamLong.lf
Labels: ci

#2545 Docs cleanup 1
  core/src/integrationTest/java/org/lflang/tests/RunSingleTest.java
  core/src/integrationTest/java/org/lflang/tests/RuntimeTest.java
  core/src/integrationTest/java/org/lflang/tests/lsp/ErrorInserter.java
  core/src/integrationTest/java/org/lflang/tests/lsp/LspTests.java
  core/src/integrationTest/java/org/lflang/tests/lsp/MockCancelIndicator.java
  core/src/integrationTest/java/org/lflang/tests/lsp/MockLanguageClient.java
  core/src/integrationTest/java/org/lflang/tests/lsp/MockReportProgress.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CArduinoTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CCppTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CFlexPRETTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CPatmosTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CSchedulerTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CVerifierTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CZephyrTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CppRos2Test.java
  core/src/integrationTest/java/org/lflang/tests/runtime/CppTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/PythonTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/RustTest.java
  core/src/integrationTest/java/org/lflang/tests/runtime/TypeScriptTest.java
  core/src/integrationTest/java/org/lflang/tests/serialization/SerializationTest.java
  core/src/main/java/org/lflang/AttributeUtils.java
  core/src/main/java/org/lflang/DefaultMessageReporter.java
  core/src/main/java/org/lflang/InferredType.java
  core/src/main/java/org/lflang/LFResourceDescriptionStrategy.java
  core/src/main/java/org/lflang/LFResourceProvider.java
  core/src/main/java/org/lflang/LFRuntimeModule.java
  core/src/main/java/org/lflang/LFStandaloneSetup.java
  core/src/main/java/org/lflang/LinguaFranca.xtext
  core/src/main/java/org/lflang/diagram/synthesis/AbstractSynthesisExtensions.java
  core/src/main/java/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java
  core/src/main/java/org/lflang/diagram/synthesis/ReactorParameterDisplayModes.java
  core/src/main/java/org/lflang/diagram/synthesis/SynthesisRegistration.java
  core/src/main/java/org/lflang/diagram/synthesis/action/AbstractAction.java
  core/src/main/java/org/lflang/diagram/synthesis/action/CollapseAllReactorsAction.java
  core/src/main/java/org/lflang/diagram/synthesis/action/ExpandAllReactorsAction.java
  core/src/main/java/org/lflang/diagram/synthesis/action/FilterCycleAction.java
  core/src/main/java/org/lflang/diagram/synthesis/action/MemorizingExpandCollapseAction.java
  core/src/main/java/org/lflang/diagram/synthesis/action/ShowCycleAction.java
  core/src/main/java/org/lflang/diagram/synthesis/postprocessor/ReactionPortAdjustment.java
  core/src/main/java/org/lflang/diagram/synthesis/postprocessor/ReactorPortAdjustment.java
  core/src/main/java/org/lflang/diagram/synthesis/styles/LinguaFrancaShapeExtensions.java
  core/src/main/java/org/lflang/diagram/synthesis/styles/LinguaFrancaStyleExtensions.java
  core/src/main/java/org/lflang/diagram/synthesis/styles/ReactorFigureComponents.java
  core/src/main/java/org/lflang/diagram/synthesis/util/CycleVisualization.java
  core/src/main/java/org/lflang/diagram/synthesis/util/InterfaceDependenciesVisualization.java
  core/src/main/java/org/lflang/diagram/synthesis/util/LayoutPostProcessing.java
  core/src/main/java/org/lflang/diagram/synthesis/util/ModeDiagrams.java
  core/src/main/java/org/lflang/diagram/synthesis/util/NamedInstanceUtil.java
  core/src/main/java/org/lflang/diagram/synthesis/util/ReactorIcons.java
  core/src/main/java/org/lflang/diagram/synthesis/util/SynthesisMessageReporter.java
  core/src/main/java/org/lflang/diagram/synthesis/util/UtilityExtensions.java
  core/src/main/resources/lib/c/EnclaveConnection.lf
Labels: docs, cleanup

#2550 Doxygen warnings
  buildSrc/src/main/groovy/org.lflang.java-conventions.gradle
  buildSrc/src/main/java/lfformat/LfFormatStep.java
  cli/lfc/src/main/java/org/lflang/cli/Lfc.java
  core/src/integrationTest/java/org/lflang/tests/lsp/ErrorInserter.java
  core/src/integrationTest/java/org/lflang/tests/lsp/LspTests.java
  core/src/main/java/org/lflang/generator/GeneratorBase.java
  core/src/main/java/org/lflang/generator/RuntimeRange.java
  core/src/main/java/org/lflang/generator/TargetTypes.java
  core/src/main/java/org/lflang/generator/c/CUtil.java
  core/src/main/java/org/lflang/generator/docker/DockerGenerator.java
  docs/Doxyfile.in
  docs/doxygen.java
  docs/replace_code_tags.py
Labels: documentation, cleanup
