Repository lf-lang/lingua-franca, pull requests merged in 2025-03, with the labels that each got.

#2477 Fix federated ZDC detection algorithm
  core/src/main/java/org/lflang/federated/generator/FederateInstance.java
Labels: compiler, c, federated, bugfix

#2479 Cache action bumped to v4
  .github/workflows/lsp-tests.yml
Labels: ci

#2484 Bumping up reactor-ts package version.
  core/src/main/resources/lib/ts/package.json
Labels: version
